version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: next
    versions:
    - 10.0.8
